package(
    default_visibility = [
        "//flash_attn_tf:__subpackages__",
    ],
)

py_library(
    name = "flash_attn_tf",
    srcs = glob(["*.py"]),
    srcs_version = "PY3",
    deps = [
        "//flash_attn_tf/python/op:flash_attn_ops",
    ],
)
