package(default_visibility = ["//visibility:public"])

py_library(
    name = "flash_attn_tf",
    srcs = glob(["**/*.py"]),
    data = ["py.typed"],
    srcs_version = "PY3",
    deps = [
        "//flash_attn_tf/python/op:flash_attn_ops",
    ],
)
